### PR TITLE
BF-001: Update README.md

### PR DESCRIPTION
**Pull request by hungphamviet**
## Ticket
Since there is no ticket management tool used, this section will be temporary ignored.

## Overview
This ticket is a simple work that's just re-editing the `README.md` file which helps better introducing repository into community.

  ## Verification Steps
1. `git checkout ###`
2. Read the modified files. No test execution needed.

### Docs
- [ ] Are changes required for docs?
  - [ ] `readme.md` was updated?
  - [ ] Additional documentation required for `docs/`?
- [x] No Doc Changes.

### CODE REVIEW

**Comment by hungphamviet** [comment]
Hi @uitnetwork ,
Please help me to review this pull request. Thanks.

**Comment by uitnetwork** [comment]
Hi @hungphamviet,

Okay. Give me some time to get familiar with Github Review process first.

**Review by uitnetwork — APPROVED** [review]
Looks good to me :)

**Comment by hungphamviet** [comment]
@uitnetwork , it's pretty good if the feature branches to be deleted once they have been merged.

**Comment by uitnetwork** [comment]
@hungphamviet okay. Got it. Thanks.

**Pull request merged**
